-- Script to fill data for quiz functionality.

-- Insert data into the `Quiz` table
INSERT INTO [dbo].[Quiz] ([Name], [Description], [CreatedAt])
VALUES
    ('Multi-Agent Systems', 'Test your knowledge of multiagent AI systems in this challenging quiz.', '2024-05-24T22:31:19'),
    ('Message Queuing Mastery', 'Dive into the intricacies of message queues and asynchronous communication.', '2024-05-24T22:31:19'),
    ('Real-Time Communication Challenges', 'Explore the nuances of building real-time applications.', '2024-05-24T22:31:19'),
    ('.NET Ecosystem Trivia', 'Quiz on the .NET ecosystem, including C#, ASP.NET, and more.', '2024-05-24T22:31:19'),
    ('Database Design and SQL', 'Test your skills in database schema design and SQL queries.', '2024-05-24T22:31:19'),
    ('AI Ethics and Bias', 'Delve into ethical considerations when working with AI models.', '2024-05-24T22:31:19'),
    ('Software Architecture Patterns', 'Assess your understanding of architectural styles like microservices, monoliths, and serverless.', '2024-05-24T22:31:19'),
    ('AI Prompting Strategies', 'Learn about effective techniques for generating AI prompts.', '2024-05-24T22:31:19'),
    ('RESTful API Concepts', 'Understand REST principles and best practices.', '2024-05-24T22:31:19'),
    ('Cloud Computing Essentials', 'Questions about cloud providers, services, and deployment.', '2024-05-24T22:31:19'),
    ('Design Patterns Challenge', 'Identify common design patterns in software development.', '2024-05-24T22:31:19'),
    ('Security Best Practices', 'Test your knowledge of secure coding practices.', '2024-05-24T22:31:19'),
    ('JavaScript Frameworks', 'Explore React, Angular, or Vue.js.', '2024-05-24T22:31:19'),
    ('Object-Oriented Programming', 'Dive into OOP concepts, inheritance, encapsulation, and polymorphism.', '2024-05-24T22:31:19'),
    ('Agile Methodologies', 'Assess your grasp of Scrum, Kanban, and Agile principles.', '2024-05-24T22:31:19'),
    ('Big Data Technologies', 'Hadoop, Spark, and data processing frameworks.', '2024-05-24T22:31:19'),
    ('DevOps Concepts', 'CI/CD pipelines, Docker, and infrastructure as code.', '2024-05-24T22:31:19'),
    ('Web APIs and OAuth', 'Understand API authentication and authorization.', '2024-05-24T22:31:19'),
    ('Software Testing Techniques', 'Covering unit testing, integration testing, and more.', '2024-05-24T22:31:19'),
    ('Microservices Challenges', 'Questions related to microservices architecture and deployment.', '2024-05-24T22:31:19'),
    ('Ollama and Local LLMs', 'Explore topics related to Ollama and local language models.', '2024-05-24T22:31:19');
GO

-- Insert data into the `Question` table
INSERT INTO [dbo].[Question] ([QuizId], [Text], [Type], [Complexity])
VALUES
    -- 
    (2, 'What is the fundamental difference between synchronous and asynchronous communication in the context of message queuing?', 0, 2),
    (2, 'Explain the concept of a message queue and how it enables asynchronous communication between applications.', 0, 2),
    (2, 'How does a message queue address the challenges of scalability in distributed systems?', 0, 2),
    (2, 'Compare Apache Kafka and RabbitMQ in terms of their core functionalities and use cases.', 0, 2),
    (2, 'What are the key strengths of Kafka as a high-throughput streaming platform?', 0, 2),
    (2, 'Describe the role of producers and consumers in a Kafka-based system.', 0, 2),
    (2, 'How does Kafka ensure data durability even in the face of server failures?', 0, 2),
    (2, 'Discuss the complexity involved in setting up and managing a Kafka cluster.', 0, 2),
    (2, 'What is the learning curve associated with understanding Kafka''s distributed architecture?', 0, 2),
    (2, 'Explain the concept of log aggregation and how Kafka facilitates it.', 0, 2),
    (2, 'What are the advantages of using JSON and Avro message formats in Kafka?', 0, 2),
    (2, 'How can RabbitMQ be described as a reliable workhorse in the message queuing space?', 0, 2),
    (2, 'What makes RabbitMQ lightweight and easy to use compared to Kafka?', 0, 2),
    (2, 'Discuss the concept of loose coupling in the context of RabbitMQ.', 0, 2),
    (2, 'How does RabbitMQ handle scenarios where a consumer becomes temporarily unavailable?', 0, 2),
    -- 
    (3, 'What is the primary objective of the WebSocket protocol?', 0, 2),
    (3, 'How does WebSocket differ from HTTP in terms of communication style?', 0, 2),
    (3, 'Explain the concept of full-duplex communication.', 0, 2),
    (3, 'What is the significance of WebSockets in driving real-time web interactions?', 0, 2),
    (3, 'Which RFC specifies the WebSocket protocol?', 0, 2),
    (3, 'Describe the mechanics of WebSockets.', 0, 2),
    (3, 'What are the benefits of using WebSockets for applications like instant messaging and live sports score updates?', 0, 2),
    (3, 'How does WebSocket handle continuous connections without reinitiating HTTP connections?', 0, 2),
    (3, 'What are the prefixes used to identify WebSocket URLs?', 0, 2),
    (3, 'What is the difference between WS and WSS in WebSocket URLs?', 0, 2),
    (3, 'Why is WebSocket considered state-preserving?', 0, 2),
    (3, 'How does WebSocket ensure uninterrupted communication between a client and server?', 0, 2),
    (3, 'Explain the handshake process during WebSocket connection initiation.', 0, 2),
    (3, 'What happens when a WebSocket connection is intentionally terminated?', 0, 2),
    (3, 'In what scenarios would you choose HTTP over WebSocket?', 0, 2),
    (3, 'What are the limitations of HTTP in terms of real-time communication?', 0, 2),
    (3, 'Can WebSocket operate over both HTTP and HTTPS?', 0, 2),
    (3, 'How does WebSocket handle data transfer between a browser and server?', 0, 2),
    (3, 'Give an example of an application that benefits from WebSocket''s bidirectional communication.', 0, 2),
    (3, 'What are some use cases where WebSockets are commonly employed?', 0, 2),
    (3, 'What is the primary purpose of SignalR?', 0, 2),
    (3, 'How does SignalR enable real-time web functionality?', 0, 2),
    (3, 'Which transport layers does SignalR support?', 0, 2),
    (3, 'What are the benefits of using SignalR for live chat and real-time dashboards?', 0, 2),
    (3, 'Explain the concept of connection management in SignalR.', 0, 2),
    (3, 'What is the role of the ASP.NET SignalR JavaScript module?', 0, 2),
    (3, 'How does SignalR handle communication between clients and servers?', 0, 2),
    (3, 'Which transport method is automatically chosen if not specified in SignalR?', 0, 2),
    (3, 'Describe the WebSocket transport layer in SignalR.', 0, 2),
    (3, 'What is the significance of Server-Sent Event (SSE) in SignalR?', 0, 2),
    (3, 'What is WebRTC, and what does it stand for?', 0, 2),
    (3, 'How does WebRTC facilitate real-time communication?', 0, 2),
    (3, 'What components are included in WebRTC?', 0, 2),
    (3, 'What type of communication can be integrated into web pages using WebRTC?', 0, 2),
    (3, 'Why is WebRTC considered a free and open-source protocol?', 0, 2),
    (3, 'How has WebRTC''s popularity increased during the COVID-19 pandemic?', 0, 2),
    (3, 'When was WebRTC fully standardized?', 0, 2),
    (3, 'What is the primary use case for WebRTC today?', 0, 2),
    (3, 'Can WebRTC be modified to suit specific purposes?', 0, 2),
    (3, 'What are some open-source WebRTC projects and frameworks?', 0, 2),
    -- 
    (4, 'What is the primary purpose of the .NET Framework?', 0, 2),
    (4, 'Which runtime was released in 2016 and can be used to create ASP.NET Core and Universal Windows Platform (UWP) applications?', 0, 2),
    (4, 'What is the main difference between .NET Core and the .NET Framework?', 0, 2),
    (4, 'Which types of applications can you build using the .NET Framework?', 0, 2),
    (4, 'What are some application types that are mainly Windows-centric when using the .NET Framework?', 0, 2),
    (4, 'What is the purpose of the Roslyn Compiler in the .NET ecosystem?', 0, 2),
    (4, 'Which runtime aims to unify development for desktop, web, cloud, mobile, gaming, IoT, and AI?', 0, 2),
    (4, 'What is the role of .NET Standard in the ecosystem?', 0, 2),
    (4, 'How does .NET Core differ from the .NET Framework in terms of cross-platform support?', 0, 2),
    (4, 'Which runtime is mainly used for Windows Forms and ASP.NET Forms and MVC applications?', 0, 2),
    (4, 'What are Portable Class Libraries, and when should you use them?', 0, 2),
    (4, 'Explain the concept of .NET Standard class libraries.', 0, 2),
    (4, 'Which runtime is the oldest and most well-known in the .NET ecosystem?', 0, 2),
    (4, 'Can you give an example of an ecosystem other than the .NET ecosystem?', 0, 2),
    (4, 'What are the roles performed by both living and nonliving organisms in an ecosystem?', 0, 2),
    (4, 'How is energy utilized and transformed within an ecosystem?', 0, 2),
    (4, 'What processes are involved in maintaining a healthy ecosystem?', 0, 2),
    (4, 'What is the goal of .NET 5, the latest runtime in the .NET Ecosystem?', 0, 2),
    (4, 'How does .NET Core contribute to modern application development?', 0, 2),
    (4, 'Which runtime should you choose when building a reusable library for cross-platform applications?', 0, 2),
    -- 
    (9, 'What does REST stand for, and who first presented it?', 0, 2),
    (9, 'What is the main difference between REST and SOAP?', 0, 2),
    (9, 'Explain the concept of a "uniform interface" in REST.', 0, 2),
    (9, 'How does REST ensure that resources are uniquely identified?', 0, 2),
    (9, 'What are the standard HTTP methods used in RESTful APIs, and what do they represent?', 0, 2),
    (9, 'Describe the "client-server" constraint in REST.', 0, 2),
    (9, 'Why is statelessness important in RESTful APIs?', 0, 2),
    (9, 'What role does hypermedia play in RESTful APIs?', 0, 2),
    (9, 'How can you manipulate resources through representations in REST?', 0, 2),
    (9, 'What does it mean for a resource representation to be self-descriptive?', 0, 2),
    (9, 'How does REST handle caching of responses?', 0, 2),
    (9, 'What is the purpose of using hyperlinks as the engine of application state?', 0, 2),
    (9, 'Explain the layered system constraint in REST.', 0, 2),
    (9, 'What are the benefits of having a uniform interface in RESTful APIs?', 0, 2),
    (9, 'How can a client discover available resources in a RESTful system?', 0, 2),
    (9, 'What are the common status codes returned by REST APIs, and what do they signify?', 0, 2),
    (9, 'How can you create a RESTful API that adheres to the principles of REST?', 0, 2),
    (9, 'What are the advantages of using RESTful APIs in microservices architectures?', 0, 2),
    (9, 'How can you handle authentication and authorization in a RESTful API?', 0, 2),
    (9, 'Provide an example of a well-designed RESTful API endpoint.', 0, 2),
    -- INSERT INTO script for Cloud Computing Essentials questions
    (10, 'What is the difference between public, private, and hybrid clouds?', 0, 2),
    (10, 'Explain the concept of elasticity in cloud computing.', 0, 2),
    (10, 'What are the essential characteristics of cloud computing according to NIST?', 0, 2),
    (10, 'Describe the service models in cloud computing (IaaS, PaaS, SaaS).', 0, 2),
    (10, 'How does virtualization play a role in cloud infrastructure?', 0, 2),
    (10, 'What is the purpose of a cloud service catalog?', 0, 2),
    (10, 'Compare and contrast horizontal scaling and vertical scaling.', 0, 2),
    (10, 'Explain the concept of multi-tenancy in cloud environments.', 0, 2),
    (10, 'What are the advantages and disadvantages of using containers (e.g., Docker) in cloud deployments?', 0, 2),
    (10, 'How does serverless computing differ from traditional server-based approaches?', 0, 2),
    (10, 'Discuss the importance of data sovereignty and its impact on cloud services.', 0, 2),
    (10, 'What is auto-scaling, and how does it work in cloud platforms?', 0, 2),
    (10, 'Describe the role of load balancers in cloud architectures.', 0, 2),
    (10, 'Explain the concept of cloud bursting.', 0, 2),
    (10, 'What are the security challenges associated with cloud computing?', 0, 2),
    (10, 'How does geo-replication enhance data availability in the cloud?', 0, 2),
    (10, 'Discuss the CAP theorem and its relevance to distributed systems in the cloud.', 0, 2),
    (10, 'What are the cost considerations when migrating to the cloud?', 0, 2),
    (10, 'Compare Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform (GCP) in terms of services and features.', 0, 2),
    (10, 'Provide an overview of serverless databases and their benefits.', 0, 2),
    -- 
    (12, 'Have you implemented proper authorization controls?', 0, 2),
    (12, 'How do you ensure that only authorized users can access specific functionality or resources?', 0, 2),
    (12, 'Have you implemented proper authentication controls?', 0, 2),
    (12, 'What mechanisms do you use to verify the identity of users?', 0, 2),
    (12, 'Do you have two-factor or multi-factor authentication in place?', 0, 2),
    (12, 'How do you enhance user authentication beyond just passwords?', 0, 2),
    (12, 'Is sensitive data encrypted?', 0, 2),
    (12, 'What encryption algorithms and key management practices do you follow?', 0, 2),
    (12, 'How do you validate user input to prevent security vulnerabilities like SQL injection or cross-site scripting (XSS)?', 0, 2),
    (12, 'How do you ensure that user-generated content is properly encoded to prevent XSS attacks?', 0, 2),
    (12, 'What protocols do you use for secure communication (e.g., HTTPS)?', 0, 2),
    (12, 'How do you handle certificates and trust validation?', 0, 2),
    (12, 'How do you handle errors without exposing sensitive information?', 0, 2),
    (12, 'Do you log errors securely?', 0, 2),
    (12, 'How do you configure security settings for your application, server, and database?', 0, 2),
    (12, 'Do you follow industry best practices?', 0, 2),
    (12, 'How do you manage user sessions securely?', 0, 2),
    (12, 'Do you handle session tokens properly?', 0, 2),
    (12, 'How do you validate and handle file uploads to prevent malicious files?', 0, 2),
    (12, 'Do you restrict file types and sizes?', 0, 2),
    (12, 'What measures do you take to secure your database (e.g., parameterized queries, stored procedures)?', 0, 2),
    (12, 'How do you protect against SQL injection?', 0, 2),
    (12, 'How do you prevent CSRF attacks?', 0, 2),
    (12, 'Do you use anti-CSRF tokens?', 0, 2),
    (12, 'How do you secure your APIs (e.g., authentication, authorization, rate limiting)?', 0, 2),
    (12, 'Do you follow OWASP API Security Top Ten guidelines?', 0, 2),
    (12, 'How often do you conduct code reviews for security?', 0, 2),
    (12, 'Do you involve security experts in the review process?', 0, 2),
    (12, 'How do you manage third-party dependencies (libraries, frameworks)?', 0, 2),
    (12, 'Do you keep them updated to avoid known vulnerabilities?', 0, 2),
    (12, 'Have you established and enforced secure coding standards within your development team?', 0, 2),
    (12, 'Do you follow guidelines such as OWASP''s Secure Coding Practices?', 0, 2),
    (12, 'How do you identify and assess potential security threats during the design phase?', 0, 2),
    (12, 'Do you prioritize security requirements based on risk?', 0, 2),
    (12, 'What types of security testing do you perform (e.g., penetration testing, static analysis, dynamic analysis)?', 0, 2),
    (12, 'How do you address identified vulnerabilities?', 0, 2),
    (12, 'Have you provided adequate software security training to your development staff?', 0, 2),
    -- 
    (15, 'What is the primary goal of Agile methodology?', 0, 2),
    (15, 'Which Agile framework emphasizes continuous improvement through regular retrospectives?', 0, 2),
    (15, 'In Scrum, what is the purpose of the Daily Standup (Daily Scrum) meeting?', 0, 2),
    (15, 'How does Kanban differ from Scrum in terms of work visualization and team roles?', 0, 2),
    (15, 'What are the four core values of the Agile Manifesto?', 0, 2),
    (15, 'Explain the concept of "sprints" in Agile project management.', 0, 2),
    (15, 'What is the role of a Product Owner in Scrum?', 0, 2),
    (15, 'How does Agile handle changing requirements during a project?', 0, 2),
    (15, 'What is the purpose of a burndown chart in Agile?', 0, 2),
    (15, 'Compare and contrast Scrum and Kanban methodologies.', 0, 2),
    (15, 'Why is cross-functional collaboration essential in Agile teams?', 0, 2),
    (15, 'What is the difference between velocity and throughput in Agile metrics?', 0, 2),
    (15, 'How does Agile address risk management?', 0, 2),
    (15, 'Describe the concept of "user stories" in Agile.', 0, 2),
    (15, 'What is the role of a Scrum Master?', 0, 2),
    (15, 'How does Agile promote transparency and visibility?', 0, 2),
    (15, 'Explain the concept of "timeboxing" in Agile.', 0, 2),
    (15, 'What is the "Definition of Done" in Scrum?', 0, 2),
    (15, 'How can Agile principles be applied beyond software development?', 0, 2),
    (15, 'Why is customer collaboration crucial in Agile projects?', 0, 2),
    -- 
    (20, 'What is the primary goal of a microservices architecture?', 0, 2),
    (20, 'How does a microservices approach differ from a monolithic architecture?', 0, 2),
    (20, 'What are the benefits of using microservices for application development?', 0, 2),
    (20, 'Explain the concept of bounded context in microservices design.', 0, 2),
    (20, 'Why is determining the optimal size for each microservice challenging?', 0, 2),
    (20, 'What are the key considerations when defining boundaries and connection points between microservices?', 0, 2),
    (20, 'How does data modeling differ in a microservices-based framework compared to a monolithic application?', 0, 2),
    (20, 'Discuss the security challenges associated with deploying microservices across multi-cloud environments.', 0, 2),
    (20, 'Why is testing a bottleneck in microservices architecture, especially due to dependencies on other services?', 0, 2),
    (20, 'What are the risks of data security within a distributed microservices framework?', 0, 2),
    (20, 'How can organizations maintain confidentiality, integrity, and privacy of user data in a microservices ecosystem?', 0, 2),
    (20, 'What challenges arise when each microservice team decides its own technology stack?', 0, 2),
    (20, 'Why is monitoring more complex for microservices-based applications compared to monolithic ones?', 0, 2),
    (20, 'What are the implications of non-transactional systems in microservices design?', 0, 2),
    (20, 'How do microservices handle data consistency and availability at scale?', 0, 2),
    (20, 'Discuss the trade-offs between microservices and traditional databases.', 0, 2),
    (20, 'What are the risks of increased complexity when transitioning from monoliths to microservices?', 0, 2),
    (20, 'How can problems in one microservice impact other interconnected services?', 0, 2),
    (20, 'What role does a DevOps culture play in successful microservices adoption?', 0, 2),
    (20, 'When should organizations avoid using microservices?', 0, 2);
GO
